# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
jobs:
  install_java:
    machine:
      image: ubuntu-2004:202008-01
    
    working_directory: ~/repo
    
    steps:
      - run:
          name: Java
          command: |
            sudo apt update
            sudo apt install default-jre -y
            java -version

    
    
workflows:
  version: 2
    installjava:
      jobs:
        - install_java:
