# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
jobs:
  installingDependencies:
    machine:
      image: ubuntu-2004:202008-01
    
    working_directory: ~/repo
    
    steps:
      
      - checkout:
          path: ~/repo

      - run:
          name: Building Image
          command: |
            docker pull ubuntu
            docker build -t vysnu/firstapp:latest .
            ls -ltr
            docker login -u=$DOCKER_UNAME -p=$DOCKER_PWD
            docker push vysnu/firstapp:latest 

    
workflows:
  version: 2
  workflowOne:
    jobs:
      - installingDependencies:
          context: uat
      
