# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
jobs:
  installingDependencies:
    machine:
      image: ubuntu-2004:202008-01
    
    working_directory: ~/repo
    
    steps:
      
      - checkout:
          path: ~/repo

      - run:
          name: Java
          command: |
            sudo apt update
            sudo apt install default-jre -y
            java -version
      
      - run:
          name: Gradle
          command: |
            VERSION=6.5.1
            wget https://services.gradle.org/distributions/gradle-${VERSION}-bin.zip -P /tmp
            sudo mkdir /opt/gradle
            sudo unzip -d /opt/gradle /tmp/gradle-${VERSION}-bin.zip
            sudo ln -s /opt/gradle/gradle-${VERSION} /opt/gradle/latest
            export GRADLE_HOME=/opt/gradle/latest
            export PATH=${GRADLE_HOME}/bin:${PATH}
            gradle -v

      - run:
          name: CopyingFiles
          command:
            scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null /home/circleci/repo/timelog.csv test@cciuatserver.centralindia.cloudapp.azure.com:/tmp/


    
    
workflows:
  version: 2
  installjava:
    jobs:
      - installingDependencies
