# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
jobs:
  installingDependencies:
    machine:
      image: ubuntu-2004:202008-01
    
    working_directory: ~/repo
    
    steps:
      - add_ssh_keys:
          fingerprints:
            - "1f:d3:b8:6a:2e:6b:f6:52:72:3d:a0:24:49:4d:60:a9"
            
      - checkout:
          path: ~/repo

      - run:
          namme: Installing sshpass
          command: |
            sudo apt-get install sshpass -y
      - run:
          name: CopyingFiles
          command: |
            pwd
            ls -ltr
            sshpass -p $pwd scp one.txt $uname@cciuatserver.centralindia.cloudapp.azure.com:/tmp/
            


    
    
workflows:
  version: 2
  workflowOne:
    jobs:
      - installingDependencies:
          context: uat
      
