version: 2.1

parameters:
  api:
    type: boolean
    default: false


executors:
  node:
    docker:
      - image: cimg/base:2023.02

jobs:
  build:
    parameters:
      package_name:
        type: string
        default: vishnu

    executor: node
    steps:
      - run: echo "<< parameters.package_name >> built."
      - run: echo "Build << parameters.package_name >> ..."

workflows:

  api:
    when: << pipeline.parameters.api >>
    jobs:
      - build:
          name: api-build
          package_name: api

