version: 2.1
jobs:
  sample:
    machine:
      image: ubuntu-2004:202008-01    
    environment:
      TAG: tag
    steps:
      - checkout
      - run: pwd && echo $tag
      # - run:
      #     name: Download
      #     command: |
      #       curl -H "Circle-Token: f3916447e1440c237b8dd4ace6124080b2125b1f" https://circleci.com/api/v1.1/project/github/vysnu96/Testing-two/latest/artifacts \
      #       | grep -o "https://[^ ]*" \
      #       > tag.txt
      #       sed -r 's/.{2}$//' tag.txt > output.txt
      #       wget --verbose --header "Circle-Token: f3916447e1440c237b8dd4ace6124080b2125b1f" --input-file=output.txt
      #       TAGNUMBER=$(cat buildtags)
      #       echo "This output is from the pipeline $TAGNUMBER"
      #       sed "s/buildnum/$TAGNUMBER/g" -i script.sh
      #       sudo sh script.sh
            
workflows:
  version: 2
  workflowOne:
    jobs:
      - sample