# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202008-01
      #docker:
      # specify the version you desire here
      #- image: circleci/openjdk:8-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4
    defaults: &defaults
    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      # Tell gradle what certs to use (because it otherwise can't figure it out)
      GRADLE_OPTS: -Djavax.net.ssl.trustStore=/usr/lib/jvm/java-11-openjdk-amd64/lib/security/cacerts -Dcom.ibm.jsse2.overrideDefaultTLS=true
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run:
          name: Download Certificate from Azure Storage Account
          command: |
            sudo apt-get update
            sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
            curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
            AZ_REPO=$(lsb_release -cs)
            echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
            sudo apt-get update
            sudo apt-get install azure-cli
            az --version
            az extension add --name storage-preview
            export AZURE_STORAGE_ACCOUNT=tcwprod
            export AZURE_STORAGE_ACCESS_KEY=4OObeB73hLa8eeiMnFmYj911xGsv14dD7kqMcRJAFMiOlhk5K2VwzbjYESacERUw/c5qT1V16Wh3U7B8zOUMOA==
            export container_name=tcw-certificates
            az storage blob directory download -c $container_name --account-name $AZURE_STORAGE_ACCOUNT -s "%2A.connected2fiber.com/server_chain.crt" -d "/home/circleci/c2f/server_chain.crt" --account-name $AZURE_STORAGE_ACCOUNT --account-key $AZURE_STORAGE_ACCESS_KEY

      - run:
          name: Updating Java Keystore for Nexus Repo.
          command: |
            #sudo ln -s /usr/lib/jvm/java-11-openjdk-amd64 /usr/local/openjdk-11
            sudo keytool -storepass changeit -cacerts -importcert -alias godaddy-root-CA -noprompt -file ~/c2f/server_chain.crt
            # sudo ln -s /usr/lib/jvm/jdk1.8.0 /usr/local/openjdk-8
            # sudo /usr/local/openjdk-8/bin/keytool -storepass changeit -keystore /usr/local/openjdk-8/jre/lib/security/cacerts -importcert -alias godaddy-root-CA -noprompt -file .circleci/c2fchain.crt

      # Install gradle 6.0.1 and build
      - run:
          name: Gradle build
          command: |
            which gradle
            wget https://downloads.gradle-dn.com/distributions/gradle-7.1-bin.zip
            sudo mkdir /opt/gradle && sudo unzip -d /opt/gradle gradle-7.1-bin.zip
            export PATH=$PATH:/opt/gradle/gradle-7.1/bin
            PATH=$(REMOVE_PART="/usr/local/gradle-6.6/bin" sh -c 'echo ":$PATH:" | sed "s@:$REMOVE_PART:@:@g;s@^:\(.*\):\$@\1@"')
            gradle -v
            gradle clean build

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

  build_deploy:
    machine:
      image: ubuntu-2004:202008-01
    defaults: &defaults
      #docker:
      # specify the version you desire here
      #- image: circleci/openjdk:8-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
    # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
      DEPLOY_BRANCH: uat
      DEPLOY_ENV: uat # The Values for this parameter will stage / uat / prod / vz-stage. No other values are allowed
      # Tell gradle what certs to use (because it otherwise can't figure it out)
      GRADLE_OPTS: -Djavax.net.ssl.trustStore=/usr/lib/jvm/java-11-openjdk-amd64/lib/security/cacerts -Dcom.ibm.jsse2.overrideDefaultTLS=true

    steps:

      - add_ssh_keys:
          fingerprints:
            - "42:dd:ce:44:3a:78:cd:f5:68:c0:d5:7a:72:ff:e9:6a"
            - "a4:e8:93:58:da:83:e7:0b:2f:be:58:f7:e2:51:83:43"
            - "eb:5d:5a:e3:36:47:e2:26:87:51:46:ef:07:4a:71:b6"
            - "e3:02:92:9b:0f:91:cd:04:f5:a1:38:05:23:c7:d8:0e" #dev@tcwstageweb01.eastus.cloudapp.azure.com
            - "37:cc:08:c5:a7:39:bb:a1:68:90:9e:66:38:75:2e:a7" #dev@preprodweb01.eastus.cloudapp.azure.com, dev@tcwprodweb01.eastus.cloudapp.azure.com
            - "28:d1:1d:3a:9e:8e:dc:69:56:a6:5b:96:39:17:db:6d" #stageweb01@ec2-34-198-25-174.compute-1.amazonaws.com
            - "cc:53:47:07:6f:11:a0:ed:a5:30:1e:f0:d5:9a:10:48" #dev@ec2-34-198-25-174.compute-1.amazonaws.com
      - checkout

      - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS

      - run:
          name: Environment Variables Checking
          command: |
            if [ "${CIRCLE_BRANCH}" == "${DEPLOY_BRANCH}" ]; then
               echo "Branch: ${DEPLOY_BRANCH} will be deployed to ${DEPLOY_ENV}"
            else
               echo "Current Branch is not equal to ${DEPLOY_BRANCH}. So deployment will be skipped."
            fi
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run:
          name: Download Certificate from Azure Storage Account
          command: |
            sudo apt-get update
            sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
            curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
            AZ_REPO=$(lsb_release -cs)
            echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
            sudo apt-get update
            sudo apt-get install azure-cli
            az --version
            az extension add --name storage-preview
            export AZURE_STORAGE_ACCOUNT=tcwprod
            export AZURE_STORAGE_ACCESS_KEY=4OObeB73hLa8eeiMnFmYj911xGsv14dD7kqMcRJAFMiOlhk5K2VwzbjYESacERUw/c5qT1V16Wh3U7B8zOUMOA==
            export container_name=tcw-certificates
            az storage blob directory download -c $container_name --account-name $AZURE_STORAGE_ACCOUNT -s "%2A.connected2fiber.com/server_chain.crt" -d "/home/circleci/c2f/server_chain.crt" --account-name $AZURE_STORAGE_ACCOUNT --account-key $AZURE_STORAGE_ACCESS_KEY

      - run:
          name: Updating Java Keystore for Nexus Repo.
          command: |
            #sudo ln -s /usr/lib/jvm/java-11-openjdk-amd64 /usr/local/openjdk-11
            sudo keytool -storepass changeit -cacerts -importcert -alias godaddy-root-CA -noprompt -file ~/c2f/server_chain.crt
            # sudo ln -s /usr/lib/jvm/jdk1.8.0 /usr/local/openjdk-8
            # sudo /usr/local/openjdk-8/bin/keytool -storepass changeit -keystore /usr/local/openjdk-8/jre/lib/security/cacerts -importcert -alias godaddy-root-CA -noprompt -file .circleci/c2fchain.crt

      # Install gradle 6.0.1 and build
      - run:
          name: Gradle build
          command: |
            wget https://downloads.gradle-dn.com/distributions/gradle-7.1-bin.zip
            sudo mkdir /opt/gradle && sudo unzip -d /opt/gradle gradle-7.1-bin.zip
            export PATH=$PATH:/opt/gradle/gradle-7.1/bin
            PATH=$(REMOVE_PART="/usr/local/gradle-6.6/bin" sh -c 'echo ":$PATH:" | sed "s@:$REMOVE_PART:@:@g;s@^:\(.*\):\$@\1@"')
            gradle -v
            gradle clean build

      # Save test results
      - store_test_results:
          path: /tmp/circleci-test-results
      # Save artifacts
      - store_artifacts:
          path: /tmp/circleci-artifacts
      - store_artifacts:
          path: /tmp/circleci-test-results

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run:
          name: Deploying
          command: 
          
workflows:
  version: 2.1
  build-approve-deploy:
    jobs:
      - build:
          context: nexus
          filters:
            branches:
              only:
                - /Release[0-9]+/
                - main
      - hold:
          type: approval
          requires:
            - build
          filters:
            branches:
              only:
                - /Release[0-9]+/
                - main
      - build_deploy:
          context: nexus
          requires:
            - hold
          filters:
            branches:
              only:
                - /Release[0-9]+/
                - main
  build-and-deploy:
    jobs:
      - build_deploy:
          context: nexus
          filters:
            branches:
              only:
                - uat
