# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
jobs:
  sample:
    machine:
      image: ubuntu-2004:202008-01    
    steps:
      - run:
          name: Download
          command: |
            curl -H "Circle-Token: f3916447e1440c237b8dd4ace6124080b2125b1f" https://circleci.com/api/v1.1/project/github/vysnu96/checkout-test/latest/artifacts \
            | grep -o "https://[^ ]*" \
            > tag.txt
            sed -r 's/.{2}$//' tag.txt > output.txt
            wget --verbose --header "Circle-Token: f3916447e1440c237b8dd4ace6124080b2125b1f" --input-file=output.txt
            ls -ltra
            cat buildtags
            
workflows:
  version: 2
  workflowOne:
    jobs:
      - sample