version: 2.1

parameters:
  api:
    type: boolean
    default: false


executors:
  node:
    docker:
      - image: circleci/node

jobs:

  build:
    parameters:
      package_name:
        type: string

    executor: node
    steps:
      - checkout:

      - run: echo "<< parameters.package_name >> built."
      - run: echo "Build << parameters.package_name >> ..."

workflows:
  version: 2

  api:
    when: << pipeline.parameters.api >>
    jobs:
      - build:
          name: api-build
          package_name: api

